### ISSUE TITLE
Checkout submodules by default?

### ISSUE THREAD

**Issue by andrjohns** [r-hub/actions#15]
Loving the new Github actions approach to rhub! One request, could the `r-hub/actions/checkout@v1` action checkout submodules by default? Or have an option to enable?

Thanks!

**Comment by gaborcsardi** [comment]
We can certainly forward options to `actions/checkout`. I am no sure if it should be the default, I would lean towards no, because it is not the default in `actions/checkout`.

We'll have a way to set additional parameters at the time of submission, or in the config of the R package, so that people don't need to change the R-hub workflow file. But it is also OK to change it, I think.

**Comment by gaborcsardi** [comment]
Done in 72ea6417d33f6874d79ac19aee7a469186ebc945
